name: build and push to dockerhub

on:
  push:
    branches:
      - master
      
  pull_request:

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  build-image:
    name: Build and push service image 
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build and push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker build -t $GITHUB_REGISTRY/tourmalinecore/real-world/real-world-auth-api:latest -t $GITHUB_REGISTRY/tourmalinecore/real-world/real-world-auth-api:${{ github.sha }} -f ./Dockerfile .
          docker push $GITHUB_REGISTRY/tourmalinecore/real-world/real-world-auth-api:latest
          docker push $GITHUB_REGISTRY/tourmalinecore/real-world/real-world-auth-api:${{ github.sha }}